version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GIT
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
#      - run:
#          name: List built libraries
#          command: 'ls -la --recursive'
      - run:
          name: Build unscrambler folder
          command: 'mkdir build'
      - run:
          name: Configure and Build unscrambler
          command: 'cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_STATIC=0 && cmake --build .'

